# @package credentials

massive:
  _target_: finance_etl.MassiveCredentials
  token: null
  token_env: MASSIVE_API_KEY

massive_flat_files:
  _target_: ccflow_etl.APIKeySecretCredentials
  api_key: null
  secret_key: null
  api_key_env: MASSIVE_API_KEY_ID
  secret_key_env: MASSIVE_API_KEY
